### ISSUE TITLE
Implement git flow

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#112]

**Comment by idmarjr** [comment]
I'm taking a deeper look at [Github Super Linter](https://github.com/github/super-linter) to help us defining a gitflow.
If you wanna learn more, [here's a blog post about it](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/).

**Comment by idmarjr** [comment]
Relevant to the topic:

- [Git Flow Is A Bad Idea](https://youtu.be/_w6TwnLCFwA)

**Comment by wlsf82** [comment]
We could have the master branch (which, by the way, could be renamed to main) as the base branch and decouple merges from deployments. Instead, we could use git tags for the deployments. I've done that recently with success.

**Comment by idmarjr** [comment]
We're closing this issue due to low importance at the moment.  
We will come back to it later 2022.
