### ISSUE TITLE
Add continuous integration tool (CI)

### ISSUE THREAD

**Issue by idmarjr** [brmodeloweb/brmodelo-app#144]
# Summary

#304 

In order to improve our deploy process, we want to integrate an automation tool.

This tool should check few routines like:
- Merge from `feature-branch` to `development`.
   - If tests are `OK`, allow merge 
- Merge from `development` to `master`
    -  If tests are `OK` automatically merge

## Possible solutions
- [Github Actions](https://github.com/features/actions)
- [GitLab CI/CD for GitHub](https://about.gitlab.com/solutions/github/)
- [CircleCI](https://circleci.com/)
- [TravisCI](https://travis-ci.org/)
- [CloudBees CodeShip](https://www.cloudbees.com/products/codeship)
- [Jenkins.io](https://www.jenkins.io/)
- [Cypress.io](https://www.cypress.io/)

# Output

T.B.D

**Comment by wlsf82** [comment]
I've experience with the first three **possible solutions**, and I favor **GitHub Actions** since the codebase is already on GitHub.

**Comment by idmarjr** [comment]
Related  #243

**Comment by idmarjr** [comment]
We're probably moving away of the branch related workflow described here:

> - Merge from `feature-branch` to `development`.
>    - If tests are `OK`, allow merge 
> - Merge from `development` to `master`
>     -  If tests are `OK` automatically merge

The idea is to have a leaner flow that remove `development` branch from the pipeline. At the time I'm writing this comment, the strategy is still not 100% defined. You can check #112 to know more about this.

**Comment by idmarjr** [comment]
@wlsf82 I'm considering keep this issue open as a aggregator for test coverage related tasks. 
If this is the case, ideally we should tag #144 in pull requests adding more tests.
What you think about this?

**Comment by wlsf82** [comment]
> @wlsf82 I'm considering keep this issue open as a aggregator for test coverage related tasks. If this is the case, ideally we should tag #144 in pull requests adding more tests. What you think about this?

This issue's description is related to CI, not really to testing.
