### ISSUE TITLE
Bulk positioning elements

### ISSUE THREAD

**Issue by jtsjunior** [brmodeloweb/brmodelo-app#150]
It would be great if I could position many elements at once. Unless such solution has been already implemented and I just don't found it yet.

**Comment by miltonbsn** [comment]
Hey @jtsjunior it is possible! Hold your shift key and select as many components you wish then move them together.

Ps. Press shift again and click a blank space on editor to unselect your previous selection.

Let me know if it works to you!

**Comment by miltonbsn** [comment]
@jtsjunior could you check it?

> Hey @jtsjunior it is possible! Hold your shift key and select as many components you wish then move them together.
> 
> Ps. Press shift again and click a blank space on editor to unselect your previous selection.
> 
> Let me know if it works to you!

@jtsjunior could you check it?

**Comment by jtsjunior** [comment]
Perfect, I've check the feature. I have to admit that it's not so intuitive, but after a while it became natural. Thanks for the explanation.
