### ISSUE TITLE
Issue with button "Gerar SQL"

### ISSUE THREAD

**Issue by dcroque** [brmodeloweb/brmodelo-app#163]
**Describe the bug**
While working on a logic model created based on a conceptual model I tried using the "Gerar SQL" button but no overlay with the SQL description shows up.

**Steps to reproduce**
Just clicking on the "Gerar SQL" button. I tried to reproduce the problem with another logic model, but when I create a new one or reimport the same model (and don't make any change) this doesn't happen.

**Expected behavior**
The app would give an output with the SQL description or an message with the error/issue with my model that it couldn't generate the SQL.

**Screenshots**

**Softwares version (please complete the following information):**
 - Arch Linux
 - Mozilla Firefox 88.0

**Additional context**

**Comment by dcroque** [comment]
After tweaking with the model I discovered that two FK elements missing the relation arrows were the cause of the problem. Still the suggestion to show the user the root of the error (and the existence of an error at all).

**Comment by idmarjr** [comment]
Hi @dcroque !
Thanks a lot for report this. Definitively we need to improve the error handling here.
I will reopen your issue so we can track this and improve it in a near future.

If you can, please add a screenshot or a short video of the problem. It help us a lot to better understand what's happening.  
Screenshots or copy+paste of console logs (If there's errors) are also welcome. 😄
