### ISSUE TITLE
Multivalued Attributes

### ISSUE THREAD

**Issue by OsvaldoLora** [brmodeloweb/brmodelo-app#169]
**Describe the solution you'd like**
I suggest adding functionality for multivalued attributes.

Thank you!

**Comment by idmarjr** [comment]
Hi @OsvaldoLora 
Could you give us more details about what you mean with _multivalued attributes_?
If you can share a draw or explain with more details it will be great to help us to prioritize it.

**Comment by miltonbsn** [comment]
@OsvaldoLora we already have this feature.. You should follow these steps:

1) select the attribute
2) change the "Cardinalidade" combo box to (0, n) or (1, n)
3) save
4) convert to logic 

![image](https://user-images.githubusercontent.com/881231/141701680-51e9649e-1fee-4baf-815a-a860e34476fe.png)

5) choose the option that suits you best

![image](https://user-images.githubusercontent.com/881231/141701719-355132c5-c000-4c71-b3c9-b411250958b7.png)
