### ISSUE TITLE
D.E.R

### ISSUE THREAD

**Issue by Gotardo-Aurelio** [brmodeloweb/brmodelo-app#171]

**Comment by idmarjr** [comment]
Oi @Gotardo-Aurelio, tudo bem?
Só gostaria de confirmar, você abriu essa _issue_ de propósito ou foi algum engano?
Caso tenha sido de propósito, você pode por favor nos dar mais detalhes sobre o problema ou sugestão?

Obrigado.

**Comment by idmarjr** [comment]
Por hora vou fechar essa _issue_ já que não temos mais detalhes
Lembrando que sempre podemos reabrir se for necessário.
