### ISSUE TITLE
Importar modelos já feitos com o aplicativo brModelo para desktop

### ISSUE THREAD

**Issue by k1vz** [brmodeloweb/brmodelo-app#176]
**Is your feature request related to a problem? Please describe.**
Não, apenas uma ideia para melhor a experiência do usuário.

**Describe the solution you'd like**
Um botão que permita que o usuário importe um arquivo (.brM3) no aplicativo web.

Além de tudo, agradeço pelo aplicativo, é bastante útil e muito bem feito, parabéns!

**Comment by idmarjr** [comment]
We're concentrating the work and discussions around this feature request at #76 
Due to that I'm closing this request for now.

**Comment by idmarjr** [comment]
Por hora temos previsão de implementar essa feature e por conta disso vou encerrar essa issue.
Mas obrigado pela sugestão 😄
