### ISSUE TITLE
Import older projects from Br Modelo 3.0

### ISSUE THREAD

**Issue by mathsou** [brmodeloweb/brmodelo-app#177]
I suggest a option to import a project from versions desktop of BR modelo, so I can continuing my work with the new functionalities.

**Comment by idmarjr** [comment]
Hi @mathsou!
Thanks for reach out!
This feature is definitively in our plan! Unfortunately It may take some time to have this in place due to other improvements we're currently working on.

Anyway, I'm merging this with #176 since both are related to the same topic ok?
