### ISSUE TITLE
o site morreu

### ISSUE THREAD

**Issue by NIE9** [brmodeloweb/brmodelo-app#187]
**Describe the bug**

**Steps to reproduce**
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Softwares version (please complete the following information):**
 - OS: [e.g. iOS10]
 - Browser: [e.g. Firefox 79.0, Opera 69.2]

**Additional context**

**Comment by miltonbsn** [comment]
Olá @NIE9. Não vejo nenhuma indisponibilidade na aplicação. Você ainda não consegue acessar?

Está  acessando por esse endereço: https://app.brmodeloweb.com?

**Comment by NIE9** [comment]
[image: Thumbnail for the video Vidyard Recording]
<https://share.vidyard.com/watch/UwD95YesxdD692uLiRG7G5?autoplay=1&vyetoken=7954e0c3-6401-4ee7-94bb-369c005429e0>
Vidyard Recording
<https://share.vidyard.com/watch/UwD95YesxdD692uLiRG7G5?autoplay=1&vyetoken=7954e0c3-6401-4ee7-94bb-369c005429e0>
Ele permanece carregando. já dei F5, sai do arquivo e entrei denovo...


Em dom., 11 de jul. de 2021 às 20:23, Milton Bittencourt de Souza Neto <
***@***.***> escreveu:

**Comment by miltonbsn** [comment]
Agora entendi! Isso tá acontecendo em todas as modelagens que você tá criando ou somente essa? 

Pode mandar a url dela aqui? E qual browser você tá tentando usar ?

**Comment by miltonbsn** [comment]
@NIE9 Encontrei e corrigi seu modelo, se puder recarregar sua página já deve funcionar.

Consegue confirmar qual navegador você está ultizando?

**Comment by NIE9** [comment]
Tudo OK.
Estava usando o Brave


Em dom., 11 de jul. de 2021 às 21:40, Milton Bittencourt de Souza Neto <
***@***.***> escreveu:

**Comment by idmarjr** [comment]
Obrigado por reportar o problema @NIE9 !
Vou fechar a _issue_ por hora. Se o problema voltar a aparecer, fica a vontade pra abrir outro ticket!.
