### ISSUE TITLE
O clique duplo em um elemento deveria abrir a janela de edição.

### ISSUE THREAD

**Issue by arthurcaccavo** [brmodeloweb/brmodelo-app#188]
O clique duplo em um elemento deveria abrir a janela de edição. Eu tive que abrir o seu TCC para descobrir como fazia para mudar o nome de um elemento.

**Comment by idmarjr** [comment]
Oi @SemnoSao 
Muito obrigado pela sugestão!

Por hora a solução que temos em mente pra mitigar esse problema é um pouco diferente.  
Você pode ver mais detalhes na issue https://github.com/brmodeloweb/brmodelo-app/issues/180

Em todo caso, vou manter essa issue aberta porque sua sugestão de melhoria faz bastante sentido e pode ser implementada em um futuro breve.

**Comment by idmarjr** [comment]
@SemnoSao A solução que comentei no #180 foi implementada e está atualmente no [ambiente de stagging](https://brmodelo-stage.herokuapp.com/). Ainda temos alguns bugs pra corrigir mas em breve isso va iestar disponível no https://app.brmodeloweb.com. Quando isso acontecer, vou fechar esse ticket.
