### ISSUE TITLE
o sistema não está convertendo para modelagem lógica corretamente

### ISSUE THREAD

**Issue by NIE9** [brmodeloweb/brmodelo-app#189]
**Describe the bug**

**Steps to reproduce**
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Softwares version (please complete the following information):**
 - OS: [e.g. iOS10]
 - Browser: [e.g. Firefox 79.0, Opera 69.2]

**Additional context**

**Comment by idmarjr** [comment]
Duplicated from #190
