### ISSUE TITLE
o sistema não está convertendo para modelagem lógica corretamente

### ISSUE THREAD

**Issue by NIE9** [brmodeloweb/brmodelo-app#190]
https://share.vidyard.com/watch/JNSUuHigsTTc6SFJvr3SV8?

**Comment by miltonbsn** [comment]
@NIE9 Seu navegador não tá bloqueando a modal? Já havia corrigido outra issue sua relacionado ao brave, tem alguma coisa nele que eventualmente quebra o seu modelo (que eu ainda não descobri o que é).

Oficialmente nós suportamos chrome e firefox, se puder testar em um dos dois pra ver se funciona, se não eu carrego sua modelagem aqui e tento corrigir, mas recomendo que passe a usar um dos recomendados por enquanto

**Comment by NIE9** [comment]
O primeiro modelo que converti hoje apareceu a modal, mas os próximos não apareceu mais. Achei que poderia ser o bloqueador de anuncio do Brave mas não é. Cheguei a testar também no Edge mas também não funcionou. Vou testar agora no crome pra ver se funciona.

**Comment by mbittencourtmeli** [comment]
Ok, vou importar ele aqui pra testar

**Comment by NIE9** [comment]
Testei no chrome também não converteu corretamente. tentei duplicar o modelo o converter a cópia e também não foi.

**Comment by miltonbsn** [comment]
É que originalmente ele já tá corrompido, já tô olhando ele aqui e já te passo

**Comment by NIE9** [comment]
ah, ok

**Comment by miltonbsn** [comment]
Mudei a categoria pra bug, não está funcionando mesmo vou começar a trabalhar nisso

**Comment by NIE9** [comment]
Ok, se eu refizer o modelo no chrome é pra funcionar?

**Comment by mbittencourtmeli** [comment]
Não, simplesmente parou de funcionara conversão mesmo, todas :( !! To investigando

**Comment by NIE9** [comment]
Certo, obrigado. Quando for corrigido me dá um retorno.

**Comment by mbittencourtmeli** [comment]
@NIE9 corrigido. Vale uma estrela no projeto pelo esforço de sexta pra ajudar a gente a popularizar o brmodeloweb? :smiley:

**Comment by idmarjr** [comment]
Fix now in production:
- #192: Hotfix conversion error
- #195: Prevent error to happen again.
