### ISSUE TITLE
Mesmo problema do #190

### ISSUE THREAD

**Issue by Eduardo-Chassot** [brmodeloweb/brmodelo-app#191]
A conversão para modelagem lógica não está funcionando corretamente, aparentemente a cardinalidade e conexões não geram automaticamente.

**Comment by miltonbsn** [comment]
@Spooky-Fivem já estou trabalhando nisso

**Comment by mbittencourtmeli** [comment]
@Spooky-Fivem corrigido

**Comment by miltonbsn** [comment]
@Spooky-Fivem corrigido

**Comment by idmarjr** [comment]
Duplicated from #190
