### ISSUE TITLE
Foco em toda a linha ao clickar em um botão

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#32]
@idmarjr sabe como eu arrumo esse efeito ?

![image](https://cloud.githubusercontent.com/assets/881231/15270067/3e4cf864-19e9-11e6-8e3b-6f9f4e411a01.png)

**Comment by idmarjr** [comment]
@miltonbsn O que exatamente tu quer dizer com "arrumo esse efeito"?
Queres tirar a cor quando um elemento estiver selecionado?

**Comment by miltonbsn** [comment]
Opa, não. Não consegui explicar muito bem. Quando eu clico no zoom por exemplo, a linha toda fica com aquele verde, como se eu tivesse clicando em tudo.
