### ISSUE TITLE
Como conectar elementos?

### ISSUE THREAD

**Issue by ThiagooMM** [brmodeloweb/brmodelo-app#383]
> Antes de fazer sua pergunta, por favor explore a documentação do BRModelo Web:
> https://docs.brmodeloweb.com
>
> Se mesmo assim você não encontrou a resposta que precisa, adicione sua pergunta a seguir:

---

### Pergunta
Como ligar um no outro colocar a linha?  
Desde já agradeço

**Comment by idmarjr** [comment]
Oi @ThiagooMM 

Você pode nos dar mais detalhes sobre a conexão que está tentando fazer?

Se possível, compartilha com a gente o link da modelagem que você está trabalhando ou um screenshot pra que a gente possa entender melhor o problema.

**Comment by idmarjr** [comment]
Estou fechando essa _issue_ por falta de informação sobre o problema.  
Lembrando que sempre podemos reabri-la se necessário. 😄
