### ISSUE TITLE
Tela para plotar modelo físico  

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#40]
Comecei a trabalhar nisso, tô vendo uma alternativa para criar algo como um editor de textos, mas isso realmente não é importante agora (o editor). Preciso só de uma página para "colar" um script sql e o título da modelagem. Por hora imagino algo como uma folha de papel.

![image](https://cloud.githubusercontent.com/assets/881231/18653693/fd48c482-7eb1-11e6-9cc5-f881e4ea3edd.png)

**Comment by idmarjr** [comment]
Ano passado em um projeto usei o https://github.com/jaredreich/pell pra implementar um editor.
Free, open source e full ES6. :)
