### ISSUE TITLE
trabalho bixo

### ISSUE THREAD

**Issue by 1misterioso** [brmodeloweb/brmodelo-app#556]
[PublicView - BRMW.pdf](https://github.com/user-attachments/files/16728745/PublicView.-.BRMW.pdf)
https://app.brmodeloweb.com/#!/publicview/66c8828c9ab8ae5889ea7d2b
https://app.brmodeloweb.com/#!/publicview/66c87cef9ab8ae5889ea7804

**Comment by idmarjr** [comment]
Oi @1misterioso !
Eu acho que você compartilhou esses links no lugar errado. 

Vou deletar esse ticket já que ele não é referente ao desenvolvimento do BRMW.,
