### ISSUE TITLE
Create reset password module

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#68]
# Summary

Once user creates his account, users can only login to the tool. There's no way to reset it's password  if needed.

# Output

- In the login page, a link to access _forgot your password?_  specific page;
- Input field to add user email;
   - Validation need to run in the server;
      - Check if user is in the database, if yes send secure link to reset password. If not show specif error;
- Private page to user setup, confirm and submit new password;

**Comment by idmarjr** [comment]
Will this be necessary if we move forward with #103 ?

**Comment by idmarjr** [comment]
> Will this be necessary if we move forward with #103 ?

Yes it will cos  we already have a userbase in place that have no connection to any social login. Those users need to be able to reset a password if needed

**Comment by idmarjr** [comment]
Work contained at #165 
Shipped to production at 08b65dc35be8829306d59b1487941b3665717025
