### ISSUE TITLE
Define development environment

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#72]
# Summary
Define what platform will be used in the future as a development environment.
Run a proper research and depper look into functionalities, pros/cos of:

- https://www.docker.com/
- https://kubernetes.io/

# Output
- Update issue with each tool analysis
- Set proper configuration for the defined platform
- Test usage
- Update Readme.md (If needed)

**Comment by idmarjr** [comment]
Good beginners guide: https://docker-curriculum.com/

**Comment by idmarjr** [comment]
Ok, looks like we have a definition. We're going with [Docker](https://www.docker.com).  
#202 introduced the basic using our old stack ([Gulp](https://gulpjs.com) based).

Next #210 will hold needed changes to the new [Webpack](https://webpack.js.org) based stack.
