### ISSUE TITLE
Add babel compiler to the project

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#73]
# Intro
In order to improve browser compatibility we want to compile JavaScript code via [Babel](https://babeljs.io/). This way we can write modern code and still ship the product to users with not that new browsers.

# Output

- Compile modern Javascript code to _old fashion_ Javascript;
- `.balbesrc`file with proper configuration;
- Update `Readme.md` (if needed);

**Comment by idmarjr** [comment]
Work in progress at [feature/webpack-migration](https://github.com/brmodeloweb/brmodelo-app/tree/feature/webpack-migration) branch
