### ISSUE TITLE
Review and fix security issues

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#74]
# Summary

Using [`npm audit`](https://docs.npmjs.com/cli/audit) run a analysis of vulnerabilities and security issues in all project dependencies. Based in this report we need to fix, at least the *High* priority items and, if possible, solve all.

Important keep in mind that some packages with security issues may be dependencies of our own dependencies. In those cases we have few options:
1. Help the project with the issue submiting a merge request to fix it (If possible since the fix can be a ton of work);
1. Decide if it worth to keep the vulnerability there and trust soon it will be fix by the dependency team
1. Choose to remove or replace the dependency from BR Modelo Web;

**Comment by idmarjr** [comment]
After previous fixes, those are the vulnerabilities we currently have in our `master`

### Jquery 2.2.4

- **[High]** Cross-Site Scripting (XSS)
- **[Moderate]** Prototype Pollution
- **[Moderate]** Cross-Site Scripting

### yargs-parser* 5.0.0

-  **[Low]** Prototype Pollution

*: `yargs-parser` is a`gulp-cli` dependency

**Comment by idmarjr** [comment]
Closed by #122

**Comment by idmarjr** [comment]
Closed by #122
