### ISSUE TITLE
Export model

### ISSUE THREAD

**Issue by miltonbsn** [brmodeloweb/brmodelo-app#75]
# Summary

From the web interface, users should be able to export model (Logic or conceptual) and save in the local machine.

- #255 
- #301 

# To be defined

- Cryptographic exported file? 
- Export proprietary format (Something like `.brmw`);

# Output 

- [x] Export endpoints #213 
- [ ] Export flow designs;
- [ ] Frontend implementation of export flow;
- [ ] Integrate frontend and endpoints;

**Comment by idmarjr** [comment]
This feature is being deprioritized.

In order to partially fulfill this demand, we're introducing the option to generate  public link to share models. To know more please check:

- #227 
- #518
