### ISSUE TITLE
Atualizar ou migrar Gulp 

### ISSUE THREAD

**Issue by feekosta** [brmodeloweb/brmodelo-app#87]
- [ ]  ~gulp-autoprefixer   ^3.1.1  →   ^7.0.1~ ([Deprecated in favor of postcss usage](https://github.com/miltonbsn/brmodelo/pull/96/commits/e49a25bccf3c68782a738eedc27dc9fa02ec4189))
- [ ] gulp-sass           ^3.0.0  →   ^4.1.0 
- [ ] gulp-sourcemaps     ^1.9.1  →   ^2.6.5

**Comment by miltonbsn** [comment]
@idmarjr do you have any suggestions on what we should do with gulp? Maybe go straight to another task runner?

**Comment by idmarjr** [comment]
Update gulp is super straight forward. (I can do it if you want)

Regarding move to another task runner, I think it depends of what you want to achieve.
You could move to [Grunt](https://gruntjs.com/), [Yarn](https://yarnpkg.com/), [Webpack](https://webpack.js.org/) or even [build everything using npm itself](https://blog.teamtreehouse.com/use-npm-task-runner).

The question here is: what's the main objective here?
