### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by feekosta** [brmodeloweb/brmodelo-app#89]
- [ ]  bootstrap           ^3.3.7  →   ~^4.5.0~ ^5.0

#106

**Comment by idmarjr** [comment]
Recently Bootstrap announced the first public Alpha of v5.0.0
https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/

Due to this I'm holding this task and also pull request #106 till further notice.

**Comment by idmarjr** [comment]
We're introducing React as a frontend framework and moving away from  Bootstrap.
